name: ${name}
version: ${version}
main: dev.shedux.extraplaceholders.ExtraPlaceholders
api-version: ${apiVersion}
load: POSTWORLD
authors: [ sheduxdev ]
depend: [PlaceholderAPI]
softdepend: [Retention]